apiVersion: v1
kind: Pod
metadata:
  name: content-engine-pod
spec:
  containers:
  - name: content-engine-container
    image: felavid/content-engine:latest
    env: 
    - name: PORT
      value: "8080"
    ports:
    - containerPort: 8080