# Generated by Django 4.2.9 on 2024-02-11 00:16

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_by_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, validators=[projects.validators.validate_project_slug]),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[projects.validators.validate_project_title]),
        ),
    ]
