# Generated by Django 4.2.9 on 2024-02-11 00:22

from django.db import migrations, models
import projects.validators

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_title_and_slug_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, validators=[projects.validators.validate_project_description]),
        ),
    ]
